In [1]:
#Testing

In [1]:
import numpy as np
A = [3,5,1,1]
print(np.eye(10)[A])

[[ 0.  0.  0.  1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  1.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.  0.  0.]]


In [25]:
X = np.random.random((6, 5))
print(X.shape)
print(X)
np.random.shuffle(X)
print(X)

(6, 5)
[[ 0.48742658  0.43218907  0.40432221  0.36158589  0.19644533]
 [ 0.07285614  0.7466888   0.32509692  0.85511881  0.60533597]
 [ 0.71075503  0.19605861  0.38063236  0.77948683  0.0714833 ]
 [ 0.41796391  0.98104948  0.75484631  0.29105199  0.44166639]
 [ 0.83000111  0.13422871  0.30585701  0.24491273  0.28177389]
 [ 0.789444    0.61166087  0.89418843  0.14697195  0.95773661]]
[[ 0.83000111  0.13422871  0.30585701  0.24491273  0.28177389]
 [ 0.71075503  0.19605861  0.38063236  0.77948683  0.0714833 ]
 [ 0.48742658  0.43218907  0.40432221  0.36158589  0.19644533]
 [ 0.07285614  0.7466888   0.32509692  0.85511881  0.60533597]
 [ 0.41796391  0.98104948  0.75484631  0.29105199  0.44166639]
 [ 0.789444    0.61166087  0.89418843  0.14697195  0.95773661]]
